version: '2.4'
networks:
  global:
    external: true
services:
  alpha-sound-client:
    container_name: alpha-sound-client
    hostname: alpha-sound-client.vengeance.svc.cluster.local
    image: pysga1996/prv_repo:alpha-sound-client
    expose:
      - 80
    ports:
      - "8000:80"
    networks:
      - global
    volumes:
      - ./:/app
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "50m"
